import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })
import { NextUIProvider } from "@nextui-org/react"
import { Logo } from "@/components/logo"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="">
      <body
        className={`flex min-h-screen flex-col items-center justify-between p-4 ${inter.className}`}
      >
        <NextUIProvider>
          <Logo />
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
